language: cpp
compiler: g++

install:
  - sudo apt-get install g++ \
                          cmake \ 
                          make 

script:
  - mkdir build && cd build && cmake ..
  - make
  - ./hello_proj

dist: xenial
os: linux
